ALTER TYPE "QuestionFeedbackLabel" ADD VALUE 'GOOD_EXAM_STYLE';
ALTER TYPE "QuestionFeedbackLabel" ADD VALUE 'TOO_EASY_LOW_VALUE';
ALTER TYPE "QuestionFeedbackLabel" ADD VALUE 'POOR_WORDING';
ALTER TYPE "QuestionFeedbackLabel" ADD VALUE 'NOT_EXAM_RELEVANT';
ALTER TYPE "QuestionFeedbackLabel" ADD VALUE 'INCORRECT_OR_UNSUPPORTED';
ALTER TYPE "QuestionFeedbackLabel" ADD VALUE 'DOCUMENT_TRIVIA';
ALTER TYPE "QuestionFeedbackLabel" ADD VALUE 'OTHER';
