import { describe, expect, it, vi } from "vitest";

vi.mock("@vercel/blob/client", () => ({
  put: vi.fn()
}));

vi.mock("next/navigation", () => ({
  useRouter: () => ({
    push: vi.fn(),
    refresh: vi.fn(),
    replace: vi.fn()
  }),
  useSearchParams: () => new URLSearchParams()
}));

vi.mock("@/lib/question-hiding/browser", () => ({
  loadHiddenQuestionIds: () => [],
  loadSuppressHideWarningPreference: () => false,
  persistHiddenQuestionIds: vi.fn(),
  persistSuppressHideWarningPreference: vi.fn()
}));

import {
  buildCreateQuestionsUrl,
  clearPersistedUploadItems,
  findRestoredUploadDocumentMatch,
  getReadyUploadDocumentIds,
  getUploadSummary,
  readPersistedUploadItems,
  RECENT_UPLOAD_BATCH_STORAGE_KEY,
  reconcilePersistedUploadItem,
  reconcileUploadItemsWithDocuments,
  restorePersistedUploadItems,
  runUploadBatch,
  shouldWarnBeforeUnloadForUploadItems,
  UPLOAD_RECONCILE_GRACE_MS,
  writePersistedUploadItems
} from "@/app/dashboard/documents/upload-form";
import {
  buildDeleteDocumentRequestInit,
  getStatusMessage,
  toggleAllSelectedDocumentIds,
  toggleSelectedDocumentId
} from "@/app/dashboard/documents/documents-list";
import { getAutogenerateDocumentIds } from "@/app/dashboard/practice/practice-client";

class MemoryStorage implements Pick<Storage, "getItem" | "setItem" | "removeItem"> {
  private values = new Map<string, string>();

  getItem(key: string) {
    return this.values.get(key) ?? null;
  }

  setItem(key: string, value: string) {
    this.values.set(key, value);
  }

  removeItem(key: string) {
    this.values.delete(key);
  }
}

describe("multi-file upload helpers", () => {
  it("summarizes per-file upload states", () => {
    expect(
      getUploadSummary([
        { status: "waiting" },
        { status: "uploading" },
        { status: "finalizing" },
        { status: "ingesting" },
        { status: "ready" },
        { status: "failed" },
        { status: "interrupted" }
      ])
    ).toEqual({
      waiting: 1,
      uploading: 2,
      processing: 1,
      ready: 1,
      failed: 1,
      interrupted: 1
    });
  });

  it("warns before unload only while local file upload can still be lost", () => {
    const file = { name: "notes.txt" } as File;

    expect(shouldWarnBeforeUnloadForUploadItems([{ status: "waiting", file }])).toBe(true);
    expect(shouldWarnBeforeUnloadForUploadItems([{ status: "uploading", file }])).toBe(true);
    expect(shouldWarnBeforeUnloadForUploadItems([{ status: "finalizing", file }])).toBe(true);
    expect(
      shouldWarnBeforeUnloadForUploadItems([{ status: "ingesting", file, documentId: "doc-1" }])
    ).toBe(false);
    expect(
      shouldWarnBeforeUnloadForUploadItems([{ status: "checking", documentId: "doc-1" }])
    ).toBe(false);
    expect(shouldWarnBeforeUnloadForUploadItems([{ status: "ready", documentId: "doc-1" }])).toBe(false);
  });

  it("continues attempting later files after one file fails", async () => {
    const attempted: string[] = [];
    const failed: string[] = [];
    const items = [
      { id: "item-1", name: "one.pdf" },
      { id: "item-2", name: "bad.exe" },
      { id: "item-3", name: "three.pdf" }
    ];

    const readyIds = await runUploadBatch({
      items,
      uploadOne: async (item) => {
        attempted.push(item.id);
        if (item.id === "item-2") {
          throw new Error("Unsupported file type.");
        }
        return { documentId: `doc-${item.id}`, status: "READY" };
      },
      onFailure: (item) => failed.push(item.id)
    });

    expect(attempted).toEqual(["item-1", "item-2", "item-3"]);
    expect(failed).toEqual(["item-2"]);
    expect(readyIds).toEqual(["doc-item-1", "doc-item-3"]);
  });

  it("builds a multi-document Create Questions selection handoff without generation settings", () => {
    const url = buildCreateQuestionsUrl({
      documentIds: ["doc-1", "doc-2", "doc-3"]
    });
    const params = new URLSearchParams(url.split("?")[1]);

    expect(url.startsWith("/dashboard/generate?")).toBe(true);
    expect(params.getAll("selectedDocumentId")).toEqual(["doc-1", "doc-2", "doc-3"]);
    expect(params.get("questionMix")).toBeNull();
    expect(params.get("count")).toBeNull();
  });

  it("writes recent upload metadata to session storage without raw files", () => {
    const storage = new MemoryStorage();

    writePersistedUploadItems(
      storage,
      [
        {
          id: "item-1",
          name: "notes.pdf",
          status: "uploading",
          documentId: undefined,
          error: undefined
        }
      ],
      1000
    );

    const raw = storage.getItem(RECENT_UPLOAD_BATCH_STORAGE_KEY);
    expect(raw).toBeTruthy();
    expect(raw).not.toContain("File");
    expect(JSON.parse(raw as string)).toEqual([
      {
        id: "item-1",
        name: "notes.pdf",
        status: "uploading",
        updatedAt: 1000
      }
    ]);
  });

  it("restores metadata without requiring raw File objects", () => {
    const restored = restorePersistedUploadItems(
      [
        {
          id: "item-1",
          name: "notes.pdf",
          status: "ready",
          documentId: "doc-1",
          updatedAt: 1000
        }
      ],
      2000
    );

    expect(restored).toEqual([
      {
        id: "item-1",
        name: "notes.pdf",
        status: "ready",
        documentId: "doc-1"
      }
    ]);
    expect("file" in restored[0]).toBe(false);
  });

  it("restores in-flight items without document IDs as checking after remount", () => {
    const restored = restorePersistedUploadItems(
      [
        { id: "waiting", name: "waiting.pdf", status: "waiting", updatedAt: 1000 },
        { id: "uploading", name: "uploading.pdf", status: "uploading", updatedAt: 1000 },
        { id: "finalizing", name: "finalizing.pdf", status: "finalizing", updatedAt: 1000 },
        { id: "ingesting", name: "ingesting.pdf", status: "ingesting", updatedAt: 1000 }
      ],
      2000
    );

    expect(restored.map((item) => item.status)).toEqual(["interrupted", "checking", "checking", "checking"]);
    expect(restored[0]?.error).toBe("This file was selected but not uploaded. Please choose it again to upload.");
    expect(restored.slice(1).every((item) => item.message?.includes("checking the document list below"))).toBe(true);
  });

  it("reconciles restored selected-only metadata to a ready server document by exact title", () => {
    const restored = restorePersistedUploadItems(
      [{ id: "item-1", name: "notes.pdf", status: "uploading", updatedAt: 1000 }],
      2000,
      [{ id: "doc-1", title: "notes.pdf", status: "READY", createdAt: "2026-05-04T10:00:00.000Z" }]
    );

    expect(restored).toEqual([
      {
        id: "item-1",
        name: "notes.pdf",
        status: "ready",
        documentId: "doc-1",
        error: undefined,
        message: "This document was uploaded and is shown below."
      }
    ]);
  });

  it("reconciles restored selected-only metadata to an ingesting server document by exact title", () => {
    expect(
      reconcilePersistedUploadItem(
        { id: "item-1", name: "notes.pdf", status: "finalizing", updatedAt: 1000 },
        [{ id: "doc-1", title: "notes.pdf", status: "PROCESSING", createdAt: "2026-05-04T10:00:00.000Z" }]
      ).status
    ).toBe("ingesting");

    expect(
      reconcilePersistedUploadItem(
        { id: "item-2", name: "queued.pdf", status: "uploading", updatedAt: 1000 },
        [{ id: "doc-2", title: "queued.pdf", status: "QUEUED", createdAt: "2026-05-04T10:00:00.000Z" }]
      ).status
    ).toBe("ingesting");
  });

  it("keeps restored in-flight metadata checking when no server document matches during grace period", () => {
    const restored = restorePersistedUploadItems(
      [{ id: "item-1", name: "missing.pdf", status: "uploading", updatedAt: 1000 }],
      2000,
      [{ id: "doc-1", title: "other.pdf", status: "READY", createdAt: "2026-05-04T10:00:00.000Z" }]
    );

    expect(restored[0]).toMatchObject({
      status: "checking",
      error: undefined
    });
  });

  it("lets waiting metadata without a document match become interrupted", () => {
    const restored = restorePersistedUploadItems(
      [{ id: "item-1", name: "missing.pdf", status: "waiting", updatedAt: 1000 }],
      2000,
      [{ id: "doc-1", title: "other.pdf", status: "READY", createdAt: "2026-05-04T10:00:00.000Z" }]
    );

    expect(restored[0]).toMatchObject({
      status: "interrupted",
      error: "This file was selected but not uploaded. Please choose it again to upload."
    });
  });

  it("marks checking metadata interrupted after the reconciliation grace period", () => {
    const restored = restorePersistedUploadItems(
      [
        {
          id: "item-1",
          name: "missing.pdf",
          status: "checking",
          updatedAt: 1000,
          checkingStartedAt: 2000
        }
      ],
      2000 + UPLOAD_RECONCILE_GRACE_MS,
      [{ id: "doc-1", title: "other.pdf", status: "READY", createdAt: "2026-05-04T10:00:00.000Z" }]
    );

    expect(restored[0]).toMatchObject({
      status: "interrupted",
      error: "This file was selected but not uploaded. Please choose it again to upload."
    });
  });

  it("reconciles checking items to ready when the document list later returns a match", () => {
    const reconciled = reconcileUploadItemsWithDocuments(
      [{ id: "item-1", name: "notes.pdf", status: "checking", checkingStartedAt: 1000 }],
      [{ id: "doc-1", title: "notes.pdf", status: "READY", createdAt: "2026-05-04T10:00:00.000Z" }],
      2000
    );

    expect(reconciled[0]).toMatchObject({
      id: "item-1",
      name: "notes.pdf",
      status: "ready",
      documentId: "doc-1"
    });
  });

  it("reconciles checking items to ingesting when the document list later returns processing states", () => {
    const processing = reconcileUploadItemsWithDocuments(
      [{ id: "item-1", name: "notes.pdf", status: "checking", checkingStartedAt: 1000 }],
      [{ id: "doc-1", title: "notes.pdf", status: "PROCESSING", createdAt: "2026-05-04T10:00:00.000Z" }],
      2000
    );
    const queued = reconcileUploadItemsWithDocuments(
      [{ id: "item-2", name: "queued.pdf", status: "checking", checkingStartedAt: 1000 }],
      [{ id: "doc-2", title: "queued.pdf", status: "QUEUED", createdAt: "2026-05-04T10:00:00.000Z" }],
      2000
    );

    expect(processing[0]).toMatchObject({ status: "ingesting", documentId: "doc-1" });
    expect(queued[0]).toMatchObject({ status: "ingesting", documentId: "doc-2" });
  });

  it("prefers the newest exact title match without fuzzy matching", () => {
    const matched = findRestoredUploadDocumentMatch(
      { id: "item-1", name: "notes.pdf", status: "uploading", updatedAt: 1000 },
      [
        { id: "older", title: "notes.pdf", status: "READY", createdAt: "2026-05-04T09:00:00.000Z" },
        { id: "fuzzy", title: "notes", status: "READY", createdAt: "2026-05-04T11:00:00.000Z" },
        { id: "newer", title: "notes.pdf", status: "PROCESSING", createdAt: "2026-05-04T10:00:00.000Z" }
      ]
    );

    expect(matched?.id).toBe("newer");
  });

  it("keeps document-backed upload items after remount", () => {
    const restored = restorePersistedUploadItems(
      [
        {
          id: "item-1",
          name: "notes.pdf",
          status: "ingesting",
          documentId: "doc-1",
          updatedAt: 1000
        }
      ],
      2000
    );

    expect(restored).toEqual([
      {
        id: "item-1",
        name: "notes.pdf",
        status: "ingesting",
        documentId: "doc-1"
      }
    ]);
  });

  it("clears persisted recent upload history", () => {
    const storage = new MemoryStorage();

    writePersistedUploadItems(
      storage,
      [{ id: "item-1", name: "notes.pdf", status: "ready", documentId: "doc-1" }],
      1000
    );
    expect(readPersistedUploadItems(storage, 2000)).toHaveLength(1);

    clearPersistedUploadItems(storage);

    expect(storage.getItem(RECENT_UPLOAD_BATCH_STORAGE_KEY)).toBeNull();
  });

  it("can generate from restored document-backed items using server readiness", () => {
    const readyIds = getReadyUploadDocumentIds(
      [
        { status: "ingesting", documentId: "doc-1" },
        { status: "ingesting", documentId: "doc-2" },
        { status: "interrupted" }
      ],
      [
        { id: "doc-1", status: "READY" },
        { id: "doc-2", status: "PROCESSING" }
      ]
    );

    expect(readyIds).toEqual(["doc-1"]);
  });

  it("lets reconciled ready items contribute to ready document generation", () => {
    const restored = restorePersistedUploadItems(
      [{ id: "item-1", name: "notes.pdf", status: "uploading", updatedAt: 1000 }],
      2000,
      [{ id: "doc-1", title: "notes.pdf", status: "READY", createdAt: "2026-05-04T10:00:00.000Z" }]
    );

    expect(getReadyUploadDocumentIds(restored)).toEqual(["doc-1"]);
  });

  it("keeps the single-file ready handoff behavior unchanged", async () => {
    const readyIds = await runUploadBatch({
      items: [{ id: "item-1", name: "one.pdf" }],
      uploadOne: async () => ({ documentId: "doc-1", status: "READY" })
    });

    expect(readyIds).toEqual(["doc-1"]);
    expect(
      buildCreateQuestionsUrl({
        documentIds: readyIds
      })
    ).toBe("/dashboard/generate?selectedDocumentId=doc-1");
  });
});

describe("document selection helpers", () => {
  it("uses reassuring processing copy for normal and long-running documents", () => {
    expect(
      getStatusMessage(
        {
          id: "doc-1",
          title: "small.pdf",
          status: "PROCESSING",
          createdAt: "2026-05-04T10:00:00.000Z",
          latestError: null
        },
        new Date("2026-05-04T10:04:00.000Z").getTime()
      )
    ).toContain("larger PDFs may take longer");

    expect(
      getStatusMessage(
        {
          id: "doc-2",
          title: "large.pdf",
          status: "PROCESSING",
          createdAt: "2026-05-04T10:00:00.000Z",
          latestError: null
        },
        new Date("2026-05-04T10:20:00.000Z").getTime()
      )
    ).toContain("taking longer than usual");
  });

  it("selects one document", () => {
    expect(toggleSelectedDocumentId([], "doc-1", true)).toEqual(["doc-1"]);
  });

  it("selects all and deselects all documents", () => {
    expect(toggleAllSelectedDocumentIds(["doc-1", "doc-2"], true)).toEqual(["doc-1", "doc-2"]);
    expect(toggleAllSelectedDocumentIds(["doc-1", "doc-2"], false)).toEqual([]);
  });

  it("deselects one document", () => {
    expect(toggleSelectedDocumentId(["doc-1", "doc-2"], "doc-1", false)).toEqual(["doc-2"]);
  });

  it("builds deletion requests with the associated-question flag", () => {
    expect(buildDeleteDocumentRequestInit(true)).toEqual({
      method: "DELETE",
      headers: {
        "content-type": "application/json"
      },
      body: JSON.stringify({ deleteAssociatedQuestions: true })
    });
  });
});

describe("practice autogeneration query parsing", () => {
  it("keeps backward compatibility with the old single-document param", () => {
    const params = new URLSearchParams("autogenerateDocumentId=doc-1");

    expect(getAutogenerateDocumentIds(params)).toEqual(["doc-1"]);
  });

  it("accepts repeated and plural multi-document params", () => {
    const params = new URLSearchParams(
      "autogenerateDocumentId=doc-1&autogenerateDocumentId=doc-2&autogenerateDocumentIds=doc-2,doc-3"
    );

    expect(getAutogenerateDocumentIds(params)).toEqual(["doc-1", "doc-2", "doc-3"]);
  });
});
