import { describe, expect, it, vi } from "vitest";

vi.mock("@vercel/blob/client", () => ({
  put: vi.fn()
}));

vi.mock("next/navigation", () => ({
  useRouter: () => ({
    push: vi.fn(),
    refresh: vi.fn(),
    replace: vi.fn()
  }),
  useSearchParams: () => new URLSearchParams()
}));

vi.mock("@/lib/question-hiding/browser", () => ({
  loadHiddenQuestionIds: () => [],
  loadSuppressHideWarningPreference: () => false,
  persistHiddenQuestionIds: vi.fn(),
  persistSuppressHideWarningPreference: vi.fn()
}));

import {
  buildAutogeneratePracticeUrl,
  getUploadSummary,
  runUploadBatch
} from "@/app/dashboard/documents/upload-form";
import { getAutogenerateDocumentIds } from "@/app/dashboard/practice/practice-client";

describe("multi-file upload helpers", () => {
  it("summarizes per-file upload states", () => {
    expect(
      getUploadSummary([
        { status: "waiting" },
        { status: "uploading" },
        { status: "finalizing" },
        { status: "ingesting" },
        { status: "ready" },
        { status: "failed" }
      ])
    ).toEqual({
      waiting: 1,
      uploading: 2,
      processing: 1,
      ready: 1,
      failed: 1
    });
  });

  it("continues attempting later files after one file fails", async () => {
    const attempted: string[] = [];
    const failed: string[] = [];
    const items = [
      { id: "item-1", name: "one.pdf" },
      { id: "item-2", name: "bad.exe" },
      { id: "item-3", name: "three.pdf" }
    ];

    const readyIds = await runUploadBatch({
      items,
      uploadOne: async (item) => {
        attempted.push(item.id);
        if (item.id === "item-2") {
          throw new Error("Unsupported file type.");
        }
        return { documentId: `doc-${item.id}`, status: "READY" };
      },
      onFailure: (item) => failed.push(item.id)
    });

    expect(attempted).toEqual(["item-1", "item-2", "item-3"]);
    expect(failed).toEqual(["item-2"]);
    expect(readyIds).toEqual(["doc-item-1", "doc-item-3"]);
  });

  it("builds a multi-document practice handoff without dropping ready documents", () => {
    const url = buildAutogeneratePracticeUrl({
      documentIds: ["doc-1", "doc-2", "doc-3"],
      questionMix: "MIXED",
      count: 3
    });
    const params = new URLSearchParams(url.split("?")[1]);

    expect(url.startsWith("/dashboard/practice?")).toBe(true);
    expect(params.getAll("autogenerateDocumentId")).toEqual(["doc-1", "doc-2", "doc-3"]);
    expect(params.get("questionMix")).toBe("MIXED");
    expect(params.get("count")).toBe("3");
  });
});

describe("practice autogeneration query parsing", () => {
  it("keeps backward compatibility with the old single-document param", () => {
    const params = new URLSearchParams("autogenerateDocumentId=doc-1");

    expect(getAutogenerateDocumentIds(params)).toEqual(["doc-1"]);
  });

  it("accepts repeated and plural multi-document params", () => {
    const params = new URLSearchParams(
      "autogenerateDocumentId=doc-1&autogenerateDocumentId=doc-2&autogenerateDocumentIds=doc-2,doc-3"
    );

    expect(getAutogenerateDocumentIds(params)).toEqual(["doc-1", "doc-2", "doc-3"]);
  });
});
