import { describe, expect, it, vi } from "vitest";

vi.mock("@vercel/blob/client", () => ({
  put: vi.fn()
}));

vi.mock("next/navigation", () => ({
  useRouter: () => ({
    push: vi.fn(),
    refresh: vi.fn(),
    replace: vi.fn()
  }),
  useSearchParams: () => new URLSearchParams()
}));

vi.mock("@/lib/question-hiding/browser", () => ({
  loadHiddenQuestionIds: () => [],
  loadSuppressHideWarningPreference: () => false,
  persistHiddenQuestionIds: vi.fn(),
  persistSuppressHideWarningPreference: vi.fn()
}));

import {
  buildAutogeneratePracticeUrl,
  clearPersistedUploadItems,
  getReadyUploadDocumentIds,
  getUploadSummary,
  readPersistedUploadItems,
  RECENT_UPLOAD_BATCH_STORAGE_KEY,
  restorePersistedUploadItems,
  runUploadBatch,
  writePersistedUploadItems
} from "@/app/dashboard/documents/upload-form";
import { getAutogenerateDocumentIds } from "@/app/dashboard/practice/practice-client";

class MemoryStorage implements Pick<Storage, "getItem" | "setItem" | "removeItem"> {
  private values = new Map<string, string>();

  getItem(key: string) {
    return this.values.get(key) ?? null;
  }

  setItem(key: string, value: string) {
    this.values.set(key, value);
  }

  removeItem(key: string) {
    this.values.delete(key);
  }
}

describe("multi-file upload helpers", () => {
  it("summarizes per-file upload states", () => {
    expect(
      getUploadSummary([
        { status: "waiting" },
        { status: "uploading" },
        { status: "finalizing" },
        { status: "ingesting" },
        { status: "ready" },
        { status: "failed" },
        { status: "interrupted" }
      ])
    ).toEqual({
      waiting: 1,
      uploading: 2,
      processing: 1,
      ready: 1,
      failed: 1,
      interrupted: 1
    });
  });

  it("continues attempting later files after one file fails", async () => {
    const attempted: string[] = [];
    const failed: string[] = [];
    const items = [
      { id: "item-1", name: "one.pdf" },
      { id: "item-2", name: "bad.exe" },
      { id: "item-3", name: "three.pdf" }
    ];

    const readyIds = await runUploadBatch({
      items,
      uploadOne: async (item) => {
        attempted.push(item.id);
        if (item.id === "item-2") {
          throw new Error("Unsupported file type.");
        }
        return { documentId: `doc-${item.id}`, status: "READY" };
      },
      onFailure: (item) => failed.push(item.id)
    });

    expect(attempted).toEqual(["item-1", "item-2", "item-3"]);
    expect(failed).toEqual(["item-2"]);
    expect(readyIds).toEqual(["doc-item-1", "doc-item-3"]);
  });

  it("builds a multi-document practice handoff without dropping ready documents", () => {
    const url = buildAutogeneratePracticeUrl({
      documentIds: ["doc-1", "doc-2", "doc-3"],
      questionMix: "MIXED",
      count: 3
    });
    const params = new URLSearchParams(url.split("?")[1]);

    expect(url.startsWith("/dashboard/practice?")).toBe(true);
    expect(params.getAll("autogenerateDocumentId")).toEqual(["doc-1", "doc-2", "doc-3"]);
    expect(params.get("questionMix")).toBe("MIXED");
    expect(params.get("count")).toBe("3");
  });

  it("writes recent upload metadata to session storage without raw files", () => {
    const storage = new MemoryStorage();

    writePersistedUploadItems(
      storage,
      [
        {
          id: "item-1",
          name: "notes.pdf",
          status: "uploading",
          documentId: undefined,
          error: undefined
        }
      ],
      1000
    );

    const raw = storage.getItem(RECENT_UPLOAD_BATCH_STORAGE_KEY);
    expect(raw).toBeTruthy();
    expect(raw).not.toContain("File");
    expect(JSON.parse(raw as string)).toEqual([
      {
        id: "item-1",
        name: "notes.pdf",
        status: "uploading",
        updatedAt: 1000
      }
    ]);
  });

  it("restores metadata without requiring raw File objects", () => {
    const restored = restorePersistedUploadItems(
      [
        {
          id: "item-1",
          name: "notes.pdf",
          status: "ready",
          documentId: "doc-1",
          updatedAt: 1000
        }
      ],
      2000
    );

    expect(restored).toEqual([
      {
        id: "item-1",
        name: "notes.pdf",
        status: "ready",
        documentId: "doc-1"
      }
    ]);
    expect("file" in restored[0]).toBe(false);
  });

  it("marks selected-only in-flight items as interrupted after remount", () => {
    const restored = restorePersistedUploadItems(
      [
        { id: "waiting", name: "waiting.pdf", status: "waiting", updatedAt: 1000 },
        { id: "uploading", name: "uploading.pdf", status: "uploading", updatedAt: 1000 },
        { id: "finalizing", name: "finalizing.pdf", status: "finalizing", updatedAt: 1000 }
      ],
      2000
    );

    expect(restored.map((item) => item.status)).toEqual(["interrupted", "interrupted", "interrupted"]);
    expect(restored.every((item) => item.error?.includes("Please select it again"))).toBe(true);
  });

  it("keeps document-backed upload items after remount", () => {
    const restored = restorePersistedUploadItems(
      [
        {
          id: "item-1",
          name: "notes.pdf",
          status: "ingesting",
          documentId: "doc-1",
          updatedAt: 1000
        }
      ],
      2000
    );

    expect(restored).toEqual([
      {
        id: "item-1",
        name: "notes.pdf",
        status: "ingesting",
        documentId: "doc-1"
      }
    ]);
  });

  it("clears persisted recent upload history", () => {
    const storage = new MemoryStorage();

    writePersistedUploadItems(
      storage,
      [{ id: "item-1", name: "notes.pdf", status: "ready", documentId: "doc-1" }],
      1000
    );
    expect(readPersistedUploadItems(storage, 2000)).toHaveLength(1);

    clearPersistedUploadItems(storage);

    expect(storage.getItem(RECENT_UPLOAD_BATCH_STORAGE_KEY)).toBeNull();
  });

  it("can generate from restored document-backed items using server readiness", () => {
    const readyIds = getReadyUploadDocumentIds(
      [
        { status: "ingesting", documentId: "doc-1" },
        { status: "ingesting", documentId: "doc-2" },
        { status: "interrupted" }
      ],
      [
        { id: "doc-1", status: "READY" },
        { id: "doc-2", status: "PROCESSING" }
      ]
    );

    expect(readyIds).toEqual(["doc-1"]);
  });
});

describe("practice autogeneration query parsing", () => {
  it("keeps backward compatibility with the old single-document param", () => {
    const params = new URLSearchParams("autogenerateDocumentId=doc-1");

    expect(getAutogenerateDocumentIds(params)).toEqual(["doc-1"]);
  });

  it("accepts repeated and plural multi-document params", () => {
    const params = new URLSearchParams(
      "autogenerateDocumentId=doc-1&autogenerateDocumentId=doc-2&autogenerateDocumentIds=doc-2,doc-3"
    );

    expect(getAutogenerateDocumentIds(params)).toEqual(["doc-1", "doc-2", "doc-3"]);
  });
});
