"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import {
  QUESTION_TYPE_LABELS,
  VISIBLE_QUESTION_TYPES,
  type VisibleQuestionType
} from "@/lib/constants/question-types";
import {
  buildGenerationSummary,
  canPracticeGeneratedQuestions,
  type GenerationOutcome
} from "@/lib/generation/job-outcome";

type Doc = { id: string; title: string };
type GenerationJobStatus = "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
type GenerationJobProgress = {
  jobId: string;
  status: GenerationJobStatus;
  currentPhase: string | null;
  passedCount: number;
  requestedCount: number;
  failedCount: number;
  outcome: GenerationOutcome;
  savedTypeCounts: {
    MCQ: number;
    TRUE_FALSE: number;
    SHORT_ANSWER: number;
  };
  errorMessage: string | null;
  completedAt: string | null;
};

const GENERATION_POLL_TIMEOUT_MS = 12 * 60 * 1000;

const difficultyOptions = [
  { value: 1, label: "Easy" },
  { value: 2, label: "Moderate" },
  { value: 3, label: "Standard exam level" },
  { value: 4, label: "Challenging" },
  { value: 5, label: "Very challenging" }
] as const;

function getAutogenerateDocumentIds(searchParams: URLSearchParams): string[] {
  const repeatedIds = searchParams.getAll("autogenerateDocumentId");
  const pluralIds = (searchParams.get("autogenerateDocumentIds") ?? "")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);

  return Array.from(new Set([...repeatedIds, ...pluralIds].filter(Boolean)));
}

function getAutogenerateQuestionTypes(questionMix: string | null): VisibleQuestionType[] {
  if (questionMix === "TRUE_FALSE") return ["TRUE_FALSE"];
  if (questionMix === "MIXED") return ["MCQ", "TRUE_FALSE"];
  return ["MCQ"];
}

export function GenerateForm({
  documents,
  maxRequestCount
}: {
  documents: Doc[];
  maxRequestCount: number;
}) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [status, setStatus] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [jobProgress, setJobProgress] = useState<GenerationJobProgress | null>(null);
  const [lastCompletedJob, setLastCompletedJob] = useState<GenerationJobProgress | null>(null);
  const [selectedDocs, setSelectedDocs] = useState<string[]>([]);
  const [difficulty, setDifficulty] = useState(3);
  const [count, setCount] = useState(5);
  const [selectedQuestionTypes, setSelectedQuestionTypes] = useState<VisibleQuestionType[]>([
    "MCQ"
  ]);
  const pollStartedAtRef = useRef<number | null>(null);
  const autoGenerationStarted = useRef(false);

  const toggleDoc = (id: string) => {
    setSelectedDocs((prev) =>
      prev.includes(id) ? prev.filter((doc) => doc !== id) : [...prev, id]
    );
  };

  const toggleQuestionType = (type: VisibleQuestionType) => {
    setSelectedQuestionTypes((prev) =>
      prev.includes(type) ? prev.filter((selected) => selected !== type) : [...prev, type]
    );
  };

  const buildTypeMixFor = (targetCount: number, questionTypes: VisibleQuestionType[]) => {
    const selected = VISIBLE_QUESTION_TYPES.filter((type) => questionTypes.includes(type));
    const mix: Record<VisibleQuestionType, number> = { MCQ: 0, TRUE_FALSE: 0 };

    if (selected.length === 0) {
      return mix;
    }

    const baseCount = Math.floor(targetCount / selected.length);
    let remainder = targetCount % selected.length;
    selected.forEach((type) => {
      mix[type] = baseCount + (remainder > 0 ? 1 : 0);
      remainder -= 1;
    });

    return mix;
  };

  const pollJob = useCallback(async (jobId: string) => {
    const response = await fetch(`/api/questions/generate/status?jobId=${encodeURIComponent(jobId)}`);
    const body = await response.json().catch(() => ({} as Partial<GenerationJobProgress>));

    if (!response.ok || !body.status) {
      throw new Error("Unable to check generation status.");
    }

    const nextProgress = body as GenerationJobProgress;
    setJobProgress(nextProgress);
    setLoading(nextProgress.status === "PENDING" || nextProgress.status === "PROCESSING");

    if (nextProgress.status === "FAILED") {
      setLastCompletedJob(nextProgress.passedCount > 0 ? nextProgress : null);
      setError(nextProgress.passedCount > 0 ? null : nextProgress.errorMessage ?? buildGenerationSummary(nextProgress));
      setStatus(nextProgress.passedCount > 0 ? buildGenerationSummary(nextProgress) : null);
      setLoading(false);
      return;
    }

    if (nextProgress.status === "COMPLETED") {
      setLastCompletedJob(nextProgress);
      setError(null);
      setStatus(buildGenerationSummary(nextProgress));
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    let cancelled = false;

    async function loadActiveJob() {
      const response = await fetch("/api/questions/generate/status");
      const body = await response.json().catch(() => null);

      if (cancelled || !response.ok || !body?.status) {
        return;
      }

      const progress = body as GenerationJobProgress;
      if (progress.status === "PENDING" || progress.status === "PROCESSING") {
        setJobProgress(progress);
        setLoading(true);
        pollStartedAtRef.current = Date.now();
        setError(null);
        setStatus("Resuming your in-progress generation.");
      } else if (progress.status === "COMPLETED") {
        setJobProgress(progress);
        setLastCompletedJob(progress);
        setLoading(false);
        setError(null);
        setStatus(buildGenerationSummary(progress));
      } else if (progress.status === "FAILED") {
        setJobProgress(progress);
        setLoading(false);
        setLastCompletedJob(progress.passedCount > 0 ? progress : null);
        setError(progress.passedCount > 0 ? null : progress.errorMessage ?? buildGenerationSummary(progress));
        setStatus(progress.passedCount > 0 ? buildGenerationSummary(progress) : null);
      }
    }

    void loadActiveJob();

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!jobProgress?.jobId || (jobProgress.status !== "PENDING" && jobProgress.status !== "PROCESSING")) {
      return;
    }

    let cancelled = false;
    const runPoll = async () => {
      if (
        pollStartedAtRef.current !== null &&
        Date.now() - pollStartedAtRef.current > GENERATION_POLL_TIMEOUT_MS
      ) {
        setLoading(false);
        setError(
          "This generation is taking longer than expected. You can refresh this page to keep viewing progress."
        );
        setStatus(null);
        setJobProgress(null);
        return;
      }

      try {
        await pollJob(jobProgress.jobId);
      } catch {
        if (!cancelled) {
          setStatus("Still waiting for an update...");
        }
      }
    };

    const interval = window.setInterval(() => {
      void runPoll();
    }, 2000);
    void runPoll();

    return () => {
      cancelled = true;
      window.clearInterval(interval);
    };
  }, [jobProgress?.jobId, jobProgress?.status, pollJob]);

  const startGeneration = useCallback(async (params: {
    documentIds: string[];
    targetCount: number;
    questionTypes: VisibleQuestionType[];
  }) => {
    setError(null);
    setStatus(null);
    setLastCompletedJob(null);
    if (params.questionTypes.length === 0) {
      setError("Choose at least one question type.");
      return;
    }
    setLoading(true);
    setJobProgress(null);
    pollStartedAtRef.current = Date.now();
    setStatus("Starting generation...");
    try {
      const response = await fetch("/api/questions/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          documentIds: params.documentIds,
          styleProfileId: null,
          presetKey: null,
          typeMix: buildTypeMixFor(params.targetCount, params.questionTypes),
          difficulty,
          count: params.targetCount
        })
      });

      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        setError(body.error ?? "Generation failed");
        setStatus(null);
        setLoading(false);
        return;
      }

      const body = await response.json().catch(() => ({} as { jobId?: string }));
      if (!body.jobId) {
        setError("Generation started, but the job could not be tracked.");
        setLoading(false);
        return;
      }

      setJobProgress({
        jobId: body.jobId,
        status: "PENDING",
        currentPhase: "Waiting to start",
        passedCount: 0,
        requestedCount: params.targetCount,
        failedCount: 0,
        outcome: "PENDING",
        savedTypeCounts: { MCQ: 0, TRUE_FALSE: 0, SHORT_ANSWER: 0 },
        errorMessage: null,
        completedAt: null
      });
      setStatus(null);
    } catch {
      setError("Generation failed. Please try again.");
      setStatus(null);
      setLoading(false);
    }
  }, [difficulty]);

  const submit = async () => {
    await startGeneration({
      documentIds: selectedDocs,
      targetCount: count,
      questionTypes: selectedQuestionTypes
    });
  };

  useEffect(() => {
    const queryDocumentIds = getAutogenerateDocumentIds(searchParams);
    if (queryDocumentIds.length === 0 || autoGenerationStarted.current) {
      return;
    }

    autoGenerationStarted.current = true;
    const readyDocumentIds = new Set(documents.map((doc) => doc.id));
    const documentIds = queryDocumentIds.filter((documentId) => readyDocumentIds.has(documentId));
    const rawCount = Number(searchParams.get("count") ?? 10);
    const targetCount = Math.min(
      maxRequestCount,
      Math.max(1, Math.round(Number.isFinite(rawCount) ? rawCount : 10))
    );
    const questionTypes = getAutogenerateQuestionTypes(searchParams.get("questionMix"));

    setSelectedDocs(documentIds);
    setCount(targetCount);
    setSelectedQuestionTypes(questionTypes);

    if (documentIds.length === 0) {
      setError("No ready documents selected.");
      router.replace("/dashboard/generate");
      return;
    }

    async function resumeOrStartGeneration() {
      const statusResponse = await fetch("/api/questions/generate/status");
      const progress = (await statusResponse.json().catch(() => null)) as GenerationJobProgress | null;

      if (
        statusResponse.ok &&
        progress?.status &&
        (progress.status === "PENDING" || progress.status === "PROCESSING")
      ) {
        setJobProgress(progress);
        setLoading(true);
        pollStartedAtRef.current = Date.now();
        setError(null);
        setStatus("Resuming your in-progress generation.");
        router.replace("/dashboard/generate");
        return;
      }

      await startGeneration({ documentIds, targetCount, questionTypes });
      router.replace("/dashboard/generate");
    }

    void resumeOrStartGeneration();
  }, [documents, maxRequestCount, router, searchParams, startGeneration]);

  const isDisabled = selectedDocs.length === 0 || selectedQuestionTypes.length === 0 || loading;
  const activeProgress =
    jobProgress && (jobProgress.status === "PENDING" || jobProgress.status === "PROCESSING")
      ? jobProgress
      : null;
  const progressTotal = Math.max(1, activeProgress?.requestedCount ?? count);
  const progressPassed = Math.min(activeProgress?.passedCount ?? 0, progressTotal);
  const progressPercent = Math.round((progressPassed / progressTotal) * 100);
  const remainingQuestions = Math.max(0, progressTotal - progressPassed);
  const estimatedSeconds = remainingQuestions * 12;
  const estimatedTime =
    estimatedSeconds >= 60
      ? `${Math.ceil(estimatedSeconds / 60)} min`
      : `${estimatedSeconds} sec`;

  return (
    <div className="space-y-4">
      <div className="space-y-2">
        <p className="text-sm font-medium text-ink">Choose study materials</p>
        <p className="text-sm text-ink/60">
          Select one or more ready study materials to generate questions from.
        </p>
        {documents.length === 0 ? (
          <p className="text-sm text-ink/60">No ready study materials available.</p>
        ) : (
          <div className="grid gap-2">
            {documents.map((doc) => (
              <label key={doc.id} className="flex items-center gap-2 text-sm text-ink/70">
                <input
                  type="checkbox"
                  checked={selectedDocs.includes(doc.id)}
                  onChange={() => toggleDoc(doc.id)}
                />
                {doc.title}
              </label>
            ))}
          </div>
        )}
      </div>

      <div className="space-y-2">
        <p className="text-sm font-medium text-ink">Question type</p>
        <div className="grid gap-3 sm:grid-cols-2">
          {VISIBLE_QUESTION_TYPES.map((type) => (
            <button
              key={type}
              type="button"
              aria-pressed={selectedQuestionTypes.includes(type)}
              onClick={() => toggleQuestionType(type)}
              className={[
                "min-h-[64px] rounded-md border px-4 py-3 text-left transition",
                selectedQuestionTypes.includes(type)
                  ? "border-accent/30 bg-accentSoft/40 text-ink ring-1 ring-accent/20"
                  : "border-ink/10 bg-white text-ink/70 hover:bg-ink/[0.02]"
              ].join(" ")}
            >
              <span className="text-sm font-medium">{QUESTION_TYPE_LABELS[type]}</span>
            </button>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-ink">Question difficulty</label>
        <p className="text-sm text-ink/60">Choose how challenging you want the questions to be.</p>
        <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">
          {difficultyOptions.map((option) => (
            <Button
              key={option.value}
              type="button"
              variant={difficulty === option.value ? "default" : "outline"}
              onClick={() => setDifficulty(option.value)}
              className="h-auto min-h-[44px] px-3 py-3 text-sm"
            >
              {option.label}
            </Button>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-ink">Target number of questions</label>
        <input
          type="number"
          min={1}
          max={maxRequestCount}
          value={count}
          onChange={(event) => {
            const rawNextCount = Number(event.target.value);
            const nextCount = Math.min(maxRequestCount, Math.max(1, rawNextCount || 1));
            setCount(nextCount);
          }}
          className="h-10 w-full rounded-md border border-ink/15 bg-white px-3 text-sm"
        />
        <p className="text-xs text-ink/55">
          We&apos;ll try to generate up to this many supported questions. Some documents may produce fewer if there isn&apos;t enough suitable evidence.
        </p>
        <p className="text-xs text-ink/55">You can create up to {maxRequestCount} questions in one run.</p>
      </div>

      <div className="space-y-2 rounded-md border border-ink/10 bg-ink/[0.02] p-4">
        <p className="text-xs text-ink/55">
          Current MCQ generation uses exactly 4 options.
        </p>
      </div>

      <Button
        onClick={submit}
        disabled={isDisabled}
        className={isDisabled ? "" : "shadow-sm ring-1 ring-accent/20"}
      >
        {loading ? "Generating..." : "Generate questions"}
      </Button>
      {selectedDocs.length === 0 && !loading ? (
        <p className="text-xs text-ink/60">
          To generate questions, select at least one study material.
        </p>
      ) : selectedQuestionTypes.length === 0 && !loading ? (
        <p className="text-xs text-ink/60">
          Select at least one question type before generating.
        </p>
      ) : null}
      {activeProgress ? (
        <div className="space-y-3 rounded-md border border-ink/10 bg-ink/[0.02] p-4">
          <div className="space-y-1">
            <div className="flex items-center justify-between gap-3 text-sm text-ink/70">
              <span>
                {progressPassed} of {progressTotal} saved
              </span>
              <span>About {estimatedTime} remaining</span>
            </div>
            <div className="h-2 overflow-hidden rounded-full bg-ink/10">
              <div
                className="h-full rounded-full bg-accent transition-all"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
          </div>
          <p className="text-sm text-ink/70">
            {activeProgress.currentPhase ?? "Preparing generation"}
          </p>
          <p className="text-xs text-ink/55">
            You can leave this page and come back; the job will keep its place.
          </p>
        </div>
      ) : null}
      {status ? <p className="text-xs text-ink/60">{status}</p> : null}
      {error ? <p className="text-xs text-danger">{error}</p> : null}
      {lastCompletedJob && !activeProgress ? (
        <div className="space-y-3 rounded-lg border border-accent/20 bg-accent/[0.05] p-4">
          <div className="space-y-1">
            {canPracticeGeneratedQuestions(lastCompletedJob) ? (
              <p className="text-sm font-semibold text-ink">Your question bank has been updated.</p>
            ) : (
              <p className="text-sm font-semibold text-ink">No new questions were added.</p>
            )}
            <p className="text-sm text-ink/70">
              {buildGenerationSummary(lastCompletedJob)}
            </p>
            {canPracticeGeneratedQuestions(lastCompletedJob) ? (
              <p className="text-xs text-ink/60">
                Saved: {lastCompletedJob.savedTypeCounts.MCQ} multiple choice,{" "}
                {lastCompletedJob.savedTypeCounts.TRUE_FALSE} true/false.
              </p>
            ) : null}
          </div>

          <div className="flex flex-wrap gap-2">
            {canPracticeGeneratedQuestions(lastCompletedJob) ? (
              <Button type="button" onClick={() => router.push("/dashboard/practice")}>
                Practise these questions
              </Button>
            ) : null}
            {canPracticeGeneratedQuestions(lastCompletedJob) ? (
              <Button type="button" variant="outline" onClick={() => router.push("/dashboard/exam")}>
                Start a mock exam
              </Button>
            ) : null}
            <Button
              type="button"
              variant={canPracticeGeneratedQuestions(lastCompletedJob) ? "outline" : "default"}
              onClick={() => {
                setLastCompletedJob(null);
                setJobProgress(null);
                setError(null);
                setStatus(null);
              }}
            >
              Generate more questions
            </Button>
          </div>
        </div>
      ) : null}
    </div>
  );
}
