"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  QUESTION_TYPE_LABELS,
  VISIBLE_QUESTION_TYPES,
  type QuestionType
} from "@/lib/constants/question-types";
import {
  getShortAnswerReviewLabel,
  sanitizeFeedbackText,
  type ShortAnswerReviewStatus
} from "@/lib/feedback/user-facing";
import {
  loadHiddenQuestionIds,
  loadSuppressHideWarningPreference,
  persistHiddenQuestionIds,
  persistSuppressHideWarningPreference
} from "@/lib/question-hiding/browser";
import {
  buildGenerationSummary,
  canPracticeGeneratedQuestions
} from "@/lib/generation/job-outcome";

type QuestionTypeFilter = QuestionType | "ALL";
type RecycleMode = "NONE" | "DUE" | "INCORRECT" | "ALL";
type QuestionFeedbackLabel =
  | "EASY"
  | "HARD"
  | "GOOD_QUESTION"
  | "DISPUTED_INCORRECT"
  | "IRRELEVANT"
  | "GOOD_EXAM_STYLE"
  | "TOO_EASY_LOW_VALUE"
  | "POOR_WORDING"
  | "NOT_EXAM_RELEVANT"
  | "INCORRECT_OR_UNSUPPORTED"
  | "DOCUMENT_TRIVIA"
  | "OTHER";

type QuestionFeedback = {
  label: QuestionFeedbackLabel;
  comment: string | null;
};

type Question = {
  id: string;
  stem: string;
  type: QuestionType;
  optionsJson?: string[] | null;
  tagsJson?: unknown;
  userFeedback: QuestionFeedback | null;
};

type FeedbackCitation = {
  label: string;
  excerpt: string;
};

type Feedback = {
  attemptId: string;
  correct: boolean;
  needsReview: boolean;
  reviewStatus: ShortAnswerReviewStatus | null;
  correctAnswer: string;
  rationale: string;
  citations: FeedbackCitation[];
  userFeedback: QuestionFeedback | null;
};

type PracticeSessionConfig = {
  questionType: QuestionTypeFilter;
  sessionLength: number;
  recycleMode: RecycleMode;
};

type AnsweredQuestion = {
  question: Question;
  answer: string;
  feedback: Feedback;
};

type GenerationJobProgress = {
  jobId: string;
  status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
  currentPhase: string | null;
  passedCount: number;
  requestedCount: number;
  errorMessage: string | null;
  completedAt: string | null;
};

const GENERATION_POLL_TIMEOUT_MS = 12 * 60 * 1000;

function normalizeSessionLength(value: number): number {
  if (!Number.isFinite(value)) return 5;
  return Math.min(50, Math.max(1, Math.round(value)));
}

function parseTags(value: unknown): string[] {
  if (!Array.isArray(value)) return [];

  return value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.trim())
    .filter(Boolean);
}

function sanitizeQuestion(question: Question | null): Question | null {
  if (!question) return null;

  return {
    ...question,
    stem: sanitizeFeedbackText(question.stem),
    optionsJson: question.optionsJson?.map((option) => sanitizeFeedbackText(option)) ?? null
  };
}

export function getAutogenerateDocumentIds(searchParams: URLSearchParams): string[] {
  const repeatedIds = searchParams.getAll("autogenerateDocumentId");
  const pluralIds = (searchParams.get("autogenerateDocumentIds") ?? "")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);

  return Array.from(new Set([...repeatedIds, ...pluralIds].filter(Boolean)));
}

const recycleModeDescriptions: Record<RecycleMode, string> = {
  NONE: "Stay with questions you have not been shown before in practice or a mock exam.",
  DUE: "Mix in questions that are scheduled to come back for revision.",
  INCORRECT: "Revisit questions you previously got wrong in practice or a mock exam.",
  ALL: "Use the full question pool, including fresh questions and ones you have seen before."
};

const questionSourceTabs: { value: RecycleMode; label: string }[] = [
  { value: "NONE", label: "New questions" },
  { value: "ALL", label: "All questions" },
  { value: "INCORRECT", label: "Previously incorrect" }
];

const questionFeedbackOptions: { label: string; value: QuestionFeedbackLabel }[] = [
  { label: "Good exam-style question", value: "GOOD_EXAM_STYLE" },
  { label: "Too easy / low value", value: "TOO_EASY_LOW_VALUE" },
  { label: "Poor wording", value: "POOR_WORDING" },
  { label: "Not exam-relevant", value: "NOT_EXAM_RELEVANT" },
  { label: "Incorrect or unsupported", value: "INCORRECT_OR_UNSUPPORTED" },
  { label: "Tests document trivia", value: "DOCUMENT_TRIVIA" },
  { label: "Other / add comment", value: "OTHER" }
];

function getQuestionFeedbackLabel(label: QuestionFeedbackLabel | null): string | null {
  if (label === "GOOD_EXAM_STYLE") return "Good exam-style question";
  if (label === "TOO_EASY_LOW_VALUE") return "Too easy / low value";
  if (label === "POOR_WORDING") return "Poor wording";
  if (label === "NOT_EXAM_RELEVANT") return "Not exam-relevant";
  if (label === "INCORRECT_OR_UNSUPPORTED") return "Incorrect or unsupported";
  if (label === "DOCUMENT_TRIVIA") return "Tests document trivia";
  if (label === "OTHER") return "Other / add comment";
  if (label === "EASY") return "Easy";
  if (label === "HARD") return "Hard";
  if (label === "GOOD_QUESTION") return "Good question";
  if (label === "DISPUTED_INCORRECT") return "Incorrect question";
  if (label === "IRRELEVANT") return "Irrelevant";
  return null;
}

function requiresFeedbackComment(label: QuestionFeedbackLabel): boolean {
  return label !== "GOOD_EXAM_STYLE";
}

function requiresNonEmptyFeedbackComment(label: QuestionFeedbackLabel): boolean {
  return label === "OTHER";
}

function getFeedbackCommentPrompt(label: QuestionFeedbackLabel | null): string {
  if (label === "OTHER") {
    return "Add a short note so we know what to fix.";
  }

  if (label === "INCORRECT_OR_UNSUPPORTED") {
    return "Optional: tell us what seems wrong or unsupported.";
  }

  if (label === "NOT_EXAM_RELEVANT") {
    return "Optional: tell us what your exam expects instead.";
  }

  if (label === "DOCUMENT_TRIVIA") {
    return "Optional: tell us why this feels like document trivia.";
  }

  return "Optional: add a short note for the beta team.";
}

export function PracticeClient() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const autoGenerationStarted = useRef(false);
  const [view, setView] = useState<"setup" | "active" | "summary">("setup");
  const [sessionConfig, setSessionConfig] = useState<PracticeSessionConfig>({
    questionType: "ALL",
    sessionLength: 5,
    recycleMode: "NONE"
  });
  const [question, setQuestion] = useState<Question | null>(null);
  const [answer, setAnswer] = useState("");
  const [feedback, setFeedback] = useState<Feedback | null>(null);
  const [results, setResults] = useState<AnsweredQuestion[]>([]);
  const [status, setStatus] = useState<string | null>(null);
  const [startTime, setStartTime] = useState<number>(Date.now());
  const [servedQuestionIds, setServedQuestionIds] = useState<string[]>([]);
  const [questionFeedback, setQuestionFeedback] = useState<QuestionFeedback | null>(null);
  const [questionFeedbackStatus, setQuestionFeedbackStatus] = useState<string | null>(null);
  const [questionFeedbackAttemptId, setQuestionFeedbackAttemptId] = useState<string | null>(null);
  const [isSavingQuestionFeedback, setIsSavingQuestionFeedback] = useState(false);
  const [pendingFeedbackLabel, setPendingFeedbackLabel] = useState<QuestionFeedbackLabel | null>(null);
  const [questionFeedbackComment, setQuestionFeedbackComment] = useState("");
  const [showQuestionStylePrompt, setShowQuestionStylePrompt] = useState(false);
  const [hiddenQuestionIds, setHiddenQuestionIds] = useState<string[]>([]);
  const [hideQuestionStatus, setHideQuestionStatus] = useState<string | null>(null);
  const [showHideQuestionWarning, setShowHideQuestionWarning] = useState(false);
  const [suppressHideWarning, setSuppressHideWarning] = useState(false);
  const [hideWarningChoice, setHideWarningChoice] = useState(false);
  const [isHidingQuestion, setIsHidingQuestion] = useState(false);
  const [autoGenerationStatus, setAutoGenerationStatus] = useState<"idle" | "generating" | "done" | "error">("idle");
  const [autoGenerationProgress, setAutoGenerationProgress] = useState<GenerationJobProgress | null>(null);

  useEffect(() => {
    setHiddenQuestionIds(loadHiddenQuestionIds());
    const suppressWarning = loadSuppressHideWarningPreference();
    setSuppressHideWarning(suppressWarning);
    setHideWarningChoice(suppressWarning);
  }, []);

  const currentQuestionNumber = Math.min(
    sessionConfig.sessionLength,
    feedback ? results.length : results.length + (question ? 1 : 0)
  );
  const isShortAnswer = question?.type === "SHORT_ANSWER";
  const shortAnswerReviewLabel = getShortAnswerReviewLabel(feedback?.reviewStatus ?? null);
  const isCorrect = feedback?.correct === true;
  const feedbackStatus = isShortAnswer
    ? shortAnswerReviewLabel ?? "Short-answer review"
    : isCorrect
      ? "Correct"
      : "Incorrect";
  const feedbackStatusClass = isShortAnswer
    ? feedback?.reviewStatus === "STRONG_MATCH"
      ? "text-accent"
      : feedback?.reviewStatus === "PARTIAL_MATCH"
        ? "text-danger"
        : "text-ink"
    : isCorrect
      ? "text-accent"
      : "text-danger";
  const isQuestionHidden = question ? hiddenQuestionIds.includes(question.id) : false;

  const loadQuestion = useCallback(async (
    excludeQuestionIds: string[],
    nextViewIfEmpty: "setup" | "summary",
    config: PracticeSessionConfig = sessionConfig
  ) => {
    setStatus("Loading question...");
    setFeedback(null);
    setAnswer("");
    setQuestionFeedback(null);
    setQuestionFeedbackStatus(null);
    setQuestionFeedbackAttemptId(null);
    setPendingFeedbackLabel(null);
    setQuestionFeedbackComment("");
    setHideQuestionStatus(null);
    setShowHideQuestionWarning(false);
    setHideWarningChoice(suppressHideWarning);
    setIsHidingQuestion(false);

    const params = new URLSearchParams({
      questionType: config.questionType,
      recycleMode: config.recycleMode
    });
    excludeQuestionIds.forEach((questionId) => params.append("excludeQuestionId", questionId));
    hiddenQuestionIds.forEach((questionId) => params.append("hiddenQuestionId", questionId));

    const response = await fetch(`/api/practice/next?${params.toString()}`);
    const body = await response.json();

    if (!response.ok) {
      setQuestion(null);
      setStatus(body.error ?? "Unable to load a practice question.");
      setQuestionFeedback(null);
      setQuestionFeedbackAttemptId(null);
      setPendingFeedbackLabel(null);
      setQuestionFeedbackComment("");
      setView(nextViewIfEmpty);
      return;
    }

    setQuestion(sanitizeQuestion(body.question ?? null));
    setStatus(body.question ? null : body.message ?? "No questions available");
    setStartTime(Date.now());
    setQuestionFeedback(body.question?.userFeedback ?? null);
    setQuestionFeedbackAttemptId(null);
    setPendingFeedbackLabel(null);
    setQuestionFeedbackComment("");
    setShowQuestionStylePrompt(false);

    if (body.question?.id) {
      setServedQuestionIds((prev) =>
        prev.includes(body.question.id) ? prev : [...prev, body.question.id]
      );
    }

    if (!body.question) {
      setView(nextViewIfEmpty);
    }
  }, [hiddenQuestionIds, sessionConfig, suppressHideWarning]);

  const startSession = async () => {
    const config = sessionConfig;
    setResults([]);
    setStatus(null);
    setServedQuestionIds([]);
    setQuestionFeedback(null);
    setQuestionFeedbackStatus(null);
    setQuestionFeedbackAttemptId(null);
    setPendingFeedbackLabel(null);
    setQuestionFeedbackComment("");
    setShowQuestionStylePrompt(false);
    setHideQuestionStatus(null);
    setShowHideQuestionWarning(false);
    setHideWarningChoice(suppressHideWarning);
    setIsHidingQuestion(false);
    setView("active");
    await loadQuestion([], "setup", config);
  };

  useEffect(() => {
    const documentIds = getAutogenerateDocumentIds(searchParams);
    if (documentIds.length === 0 || autoGenerationStarted.current) {
      return;
    }

    autoGenerationStarted.current = true;
    const questionMix = searchParams.get("questionMix");
    const rawCount = Number(searchParams.get("count") ?? 10);
    const requestedCount = Math.min(
      30,
      Math.max(1, Math.round(Number.isFinite(rawCount) ? rawCount : 10))
    );
    const typeMix =
      questionMix === "TRUE_FALSE"
        ? { MCQ: 0, TRUE_FALSE: requestedCount }
        : questionMix === "MIXED"
          ? {
              MCQ: Math.ceil(requestedCount / 2),
              TRUE_FALSE: Math.floor(requestedCount / 2)
            }
          : { MCQ: requestedCount, TRUE_FALSE: 0 };
    const nextConfig: PracticeSessionConfig = {
      questionType: "ALL",
      sessionLength: requestedCount,
      recycleMode: "ALL"
    };

    let cancelled = false;

    async function generateUploadedDocumentQuestions() {
      setAutoGenerationStatus("generating");
      setView("setup");
      setQuestion(null);
      setFeedback(null);
      setResults([]);
      setStatus(
        "Preparing questions from your document. Small documents often process within a few minutes; larger PDFs may take longer. You can leave this page and come back."
      );

      try {
        const response = await fetch("/api/questions/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            documentIds,
            styleProfileId: null,
            presetKey: null,
            typeMix,
            difficulty: 3,
            count: requestedCount
          })
        });
        const body = await response.json().catch(() => ({} as { jobId?: string; error?: string }));

        if (cancelled) {
          return;
        }

        if (!response.ok) {
          setAutoGenerationStatus("error");
          setStatus(body.error ?? "We couldn't generate questions from this upload yet.");
          return;
        }

        if (!body.jobId) {
          setAutoGenerationStatus("error");
          setStatus("We couldn't track this generation job.");
          return;
        }

        setAutoGenerationProgress({
          jobId: body.jobId,
          status: "PENDING",
          currentPhase: "Waiting to start",
          passedCount: 0,
          requestedCount,
          errorMessage: null,
          completedAt: null
        });

        let completedProgress: GenerationJobProgress | null = null;
        const pollStartedAt = Date.now();
        while (!cancelled) {
          if (Date.now() - pollStartedAt > GENERATION_POLL_TIMEOUT_MS) {
            setAutoGenerationStatus("error");
            setStatus(
              "This generation is taking longer than expected. You can refresh this page or open Practice to check for saved questions."
            );
            return;
          }

          await new Promise((resolve) => window.setTimeout(resolve, 2000));
          const statusResponse = await fetch(
            `/api/questions/generate/status?jobId=${encodeURIComponent(body.jobId)}`
          );
          const progress = (await statusResponse.json().catch(() => null)) as GenerationJobProgress | null;

          if (!statusResponse.ok || !progress?.status) {
            setStatus("Still waiting for your questions...");
            continue;
          }

          setAutoGenerationProgress(progress);

          if (progress.status === "FAILED") {
            if (canPracticeGeneratedQuestions(progress)) {
              completedProgress = progress;
              setAutoGenerationStatus("done");
              setStatus(buildGenerationSummary(progress));
              break;
            }
            setAutoGenerationStatus("error");
            setStatus(progress.errorMessage ?? buildGenerationSummary(progress));
            return;
          }

          if (progress.status === "COMPLETED") {
            completedProgress = progress;
            setAutoGenerationStatus("done");
            setStatus(buildGenerationSummary(progress));
            break;
          }

          setStatus(progress.currentPhase ?? "Generating your questions...");
        }

        if (cancelled) {
          return;
        }

        if (completedProgress && !canPracticeGeneratedQuestions(completedProgress)) {
          setView("setup");
          return;
        }

        setSessionConfig(nextConfig);
        router.replace("/dashboard/practice");
        setView("active");
        await loadQuestion([], "setup", nextConfig);
      } catch {
        if (!cancelled) {
          setAutoGenerationStatus("error");
          setStatus("We couldn't generate questions from this upload yet.");
        }
      }
    }

    void generateUploadedDocumentQuestions();

    return () => {
      cancelled = true;
    };
  }, [loadQuestion, router, searchParams]);

  const resetSession = () => {
    setView("setup");
    setQuestion(null);
    setAnswer("");
    setFeedback(null);
    setResults([]);
    setStatus(null);
    setStartTime(Date.now());
    setServedQuestionIds([]);
    setQuestionFeedback(null);
    setQuestionFeedbackStatus(null);
    setQuestionFeedbackAttemptId(null);
    setPendingFeedbackLabel(null);
    setQuestionFeedbackComment("");
    setShowQuestionStylePrompt(false);
    setHideQuestionStatus(null);
    setShowHideQuestionWarning(false);
    setHideWarningChoice(suppressHideWarning);
    setIsHidingQuestion(false);
  };

  const endSession = () => {
    setQuestion(null);
    setAnswer("");
    setFeedback(null);
    setView(results.length > 0 ? "summary" : "setup");
    setStatus(results.length > 0 ? null : status);
  };

  const submit = async () => {
    if (!question) return;

    const submittedQuestion = question;
    const submittedAnswer = answer;
    const timeSpentSec = Math.round((Date.now() - startTime) / 1000);

    const response = await fetch("/api/practice/answer", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ questionId: submittedQuestion.id, answer: submittedAnswer, timeSpentSec })
    });

    const body = await response.json();
    if (!response.ok) {
      setStatus(body.error ?? "Unable to submit your answer.");
      return;
    }

    setFeedback(body);
    setResults((prev) => [
      ...prev,
      {
        question: submittedQuestion,
        answer: submittedAnswer,
        feedback: body
      }
    ]);
    setQuestionFeedback(body.userFeedback ?? submittedQuestion.userFeedback ?? null);
    setQuestionFeedbackAttemptId(body.attemptId ?? null);
    setQuestionFeedbackStatus(null);
    setPendingFeedbackLabel(null);
    setQuestionFeedbackComment(body.userFeedback?.comment ?? submittedQuestion.userFeedback?.comment ?? "");
    setShowQuestionStylePrompt(false);
  };

  const moveToNextQuestion = async () => {
    if (results.length >= sessionConfig.sessionLength) {
      setQuestion(null);
      setAnswer("");
      setFeedback(null);
      setView("summary");
      return;
    }

    await loadQuestion(servedQuestionIds, "summary");
  };

  const saveQuestionFeedback = async (label: QuestionFeedbackLabel, comment?: string) => {
    if (!question || !feedback) return;

    setIsSavingQuestionFeedback(true);
    setQuestionFeedbackStatus("Saving your feedback...");

    const response = await fetch("/api/practice/feedback", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        questionId: question.id,
        attemptId: questionFeedbackAttemptId ?? feedback.attemptId,
        label,
        comment
      })
    });

    const body = await response.json();

    if (!response.ok) {
      setQuestionFeedbackStatus(body.error ?? "Unable to save your feedback right now.");
      setIsSavingQuestionFeedback(false);
      return;
    }

    setQuestionFeedback(body.feedback ?? { label, comment: null });
    setQuestionFeedbackStatus(
      body.message ??
        `Saved as ${getQuestionFeedbackLabel(body.feedback?.label ?? label) ?? "feedback"}.`
    );
    setPendingFeedbackLabel(null);
    setQuestionFeedbackComment(body.feedback?.comment ?? comment ?? "");
    setShowQuestionStylePrompt(Boolean(body.shouldShowQuestionStylePrompt));
    setIsSavingQuestionFeedback(false);
  };

  const startQuestionFeedback = (label: QuestionFeedbackLabel) => {
    setQuestionFeedbackStatus(null);

    if (requiresFeedbackComment(label)) {
      setPendingFeedbackLabel(label);
      setQuestionFeedbackComment(
        questionFeedback?.label === label ? (questionFeedback.comment ?? "") : ""
      );
      return;
    }

    void saveQuestionFeedback(label);
  };

  const submitQuestionFeedbackWithComment = () => {
    if (!pendingFeedbackLabel) return;
    if (requiresNonEmptyFeedbackComment(pendingFeedbackLabel) && !questionFeedbackComment.trim()) {
      setQuestionFeedbackStatus("Add a short comment for Other feedback.");
      return;
    }

    void saveQuestionFeedback(pendingFeedbackLabel, questionFeedbackComment);
  };

  const applyHideQuestion = async () => {
    if (!question) return;

    setIsHidingQuestion(true);
    setHideQuestionStatus("Hiding question...");

    const response = await fetch("/api/questions/hide", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        questionId: question.id
      })
    });

    const body = await response.json();

    if (!response.ok) {
      setHideQuestionStatus(body.error ?? "Unable to hide this question right now.");
      setIsHidingQuestion(false);
      return;
    }

    const nextHiddenQuestionIds = hiddenQuestionIds.includes(question.id)
      ? hiddenQuestionIds
      : [...hiddenQuestionIds, question.id];

    setHiddenQuestionIds(nextHiddenQuestionIds);
    persistHiddenQuestionIds(nextHiddenQuestionIds);

    if (hideWarningChoice) {
      setSuppressHideWarning(true);
      persistSuppressHideWarningPreference(true);
    }

    setShowHideQuestionWarning(false);
    setHideQuestionStatus(
      body.message ?? "We’ll hide this question from your future practice and mock exams."
    );
    setQuestionFeedbackStatus(null);
    setIsHidingQuestion(false);
  };

  const startHideQuestion = () => {
    if (!question || isQuestionHidden || isHidingQuestion) return;

    setHideQuestionStatus(null);
    setPendingFeedbackLabel(null);

    if (suppressHideWarning) {
      void applyHideQuestion();
      return;
    }

    setHideWarningChoice(false);
    setShowHideQuestionWarning(true);
  };

  const totalAnswered = results.length;
  const objectiveResults = results.filter((item) => item.question.type !== "SHORT_ANSWER");
  const shortAnswerResults = results.filter((item) => item.question.type === "SHORT_ANSWER");
  const objectiveTotal = objectiveResults.length;
  const objectiveCorrect = objectiveResults.filter((item) => item.feedback.correct).length;
  const objectiveIncorrect = objectiveTotal - objectiveCorrect;
  const shortAnswerReviewed = shortAnswerResults.filter((item) => item.feedback.reviewStatus !== null).length;
  const shortAnswerStrongMatch = shortAnswerResults.filter(
    (item) => item.feedback.reviewStatus === "STRONG_MATCH"
  ).length;
  const shortAnswerPartialMatch = shortAnswerResults.filter(
    (item) => item.feedback.reviewStatus === "PARTIAL_MATCH"
  ).length;
  const shortAnswerNeedsReview = shortAnswerResults.filter(
    (item) => item.feedback.reviewStatus === "NEEDS_REVIEW"
  ).length;

  const incorrectTopicCounts = results.reduce<Record<string, number>>((acc, item) => {
    if (item.feedback.correct) return acc;

    for (const tag of parseTags(item.question.tagsJson)) {
      acc[tag] = (acc[tag] ?? 0) + 1;
    }

    return acc;
  }, {});

  const topIncorrectTopic = Object.entries(incorrectTopicCounts).sort((a, b) => b[1] - a[1])[0] ?? null;

  return (
    <div className="space-y-4">
      {view === "setup" ? (
        <div className="space-y-4">
          <div className="grid gap-4 text-sm md:grid-cols-2">
            <label className="grid gap-2 rounded-2xl border border-ink/10 bg-ink/[0.02] p-4">
              <span className="font-medium text-ink">Question type</span>
              <span className="text-xs text-ink/55">Choose one question type or practise a mixed set.</span>
              <span className="text-xs text-ink/55">
                Beta supports multiple choice and true/false. More types coming.
              </span>
              <select
                value={sessionConfig.questionType}
                onChange={(event) =>
                  setSessionConfig((prev) => ({
                    ...prev,
                    questionType: event.target.value as QuestionTypeFilter
                  }))
                }
                className="h-10 rounded-md border border-ink/15 bg-white px-3 text-ink"
              >
                <option value="ALL">All supported types</option>
                {VISIBLE_QUESTION_TYPES.map((type) => (
                  <option key={type} value={type}>
                    {QUESTION_TYPE_LABELS[type]}
                  </option>
                ))}
              </select>
            </label>

            <div className="grid gap-2 rounded-2xl border border-ink/10 bg-ink/[0.02] p-4">
              <span className="font-medium text-ink">Questions this session</span>
              <span className="text-xs text-ink/55">Set how many questions you want to work through.</span>
              <div className="flex flex-wrap gap-2">
                {[5, 10, 20].map((length) => (
                  <Button
                    key={length}
                    type="button"
                    variant={sessionConfig.sessionLength === length ? "default" : "outline"}
                    size="sm"
                    onClick={() =>
                      setSessionConfig((prev) => ({
                        ...prev,
                        sessionLength: length
                      }))
                    }
                  >
                    {length}
                  </Button>
                ))}
              </div>
              <input
                type="number"
                min={1}
                max={50}
                value={sessionConfig.sessionLength}
                onChange={(event) =>
                  setSessionConfig((prev) => ({
                    ...prev,
                    sessionLength: normalizeSessionLength(Number(event.target.value))
                  }))
                }
                className="h-10 w-28 rounded-md border border-ink/15 px-3 text-ink"
              />
            </div>

            <div className="grid gap-2 rounded-2xl border border-ink/10 bg-ink/[0.02] p-4 md:col-span-2">
              <span className="font-medium text-ink">Question source</span>
              <span className="text-xs text-ink/55">
                Choose whether to stay with fresh questions, revisit past mistakes, or draw from
                everything available.
              </span>
              <div className="flex flex-wrap gap-2">
                {questionSourceTabs.map((tab) => (
                  <Button
                    key={tab.value}
                    type="button"
                    size="sm"
                    variant={sessionConfig.recycleMode === tab.value ? "default" : "outline"}
                    onClick={() =>
                      setSessionConfig((prev) => ({
                        ...prev,
                        recycleMode: tab.value
                      }))
                    }
                  >
                    {tab.label}
                  </Button>
                ))}
              </div>
              <input
                type="hidden"
                value={sessionConfig.recycleMode}
                onChange={(event) =>
                  setSessionConfig((prev) => ({
                    ...prev,
                    recycleMode: event.target.value as RecycleMode
                  }))
                }
              />
              <p className="text-xs text-ink/55">{recycleModeDescriptions[sessionConfig.recycleMode]}</p>
            </div>
          </div>

          {autoGenerationStatus === "generating" ? (
            <div className="space-y-3 rounded-md border border-ink/10 bg-ink/[0.02] p-4">
              <div className="flex items-center gap-3">
                <span className="h-4 w-4 animate-spin rounded-full border-2 border-ink/20 border-t-accent" />
                <p className="text-sm text-ink/70">Generating your questions...</p>
              </div>
              {autoGenerationProgress ? (
                <div className="space-y-1">
                  <div className="flex items-center justify-between gap-3 text-xs text-ink/60">
                    <span>
                      {autoGenerationProgress.passedCount} of {autoGenerationProgress.requestedCount} saved
                    </span>
                    <span>
                      About{" "}
                      {Math.ceil(
                        (Math.max(
                          0,
                          autoGenerationProgress.requestedCount - autoGenerationProgress.passedCount
                        ) *
                          12) /
                          60
                      )}{" "}
                      min remaining
                    </span>
                  </div>
                  <div className="h-2 overflow-hidden rounded-full bg-ink/10">
                    <div
                      className="h-full rounded-full bg-accent transition-all"
                      style={{
                        width: `${Math.round(
                          (Math.min(
                            autoGenerationProgress.passedCount,
                            autoGenerationProgress.requestedCount
                          ) /
                            Math.max(1, autoGenerationProgress.requestedCount)) *
                            100
                        )}%`
                      }}
                    />
                  </div>
                  <p className="text-xs text-ink/60">
                    {autoGenerationProgress.currentPhase ?? "Preparing generation"}
                  </p>
                </div>
              ) : null}
            </div>
          ) : (
            <Button onClick={startSession} className="shadow-sm">
              Start practice session
            </Button>
          )}
          {status ? <p className="text-sm text-ink/60">{status}</p> : null}
        </div>
      ) : null}

      {view === "active" ? (
        <div className="space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-ink/10 bg-ink/[0.02] px-4 py-3">
            <p className="text-sm text-ink/60">
              Question {currentQuestionNumber} of {sessionConfig.sessionLength}
            </p>
            <Button type="button" variant="outline" size="sm" onClick={endSession}>
              End session
            </Button>
          </div>

          {question ? (
            <div className="space-y-4">
              <div>
                <p className="text-xl font-semibold leading-8 tracking-tight text-ink">
                  {question.stem}
                </p>
              </div>
              {question.type === "MCQ" || question.type === "TRUE_FALSE" ? (
                <div className="space-y-2">
                  {(question.optionsJson ?? []).map((option) => (
                    <label key={option} className="flex items-center gap-2 text-sm text-ink/70">
                      <input
                        type="radio"
                        name={question.id}
                        value={option}
                        checked={answer === option}
                        disabled={feedback !== null}
                        onChange={() => setAnswer(option)}
                      />
                      {sanitizeFeedbackText(option)}
                    </label>
                  ))}
                </div>
              ) : (
                <Textarea
                  value={answer}
                  disabled={feedback !== null}
                  onChange={(event) => setAnswer(event.target.value)}
                />
              )}

              {!feedback ? (
                <Button onClick={submit} disabled={!answer.trim()}>
                  Submit answer
                </Button>
              ) : (
                <div className="rounded-2xl border border-ink/10 bg-white p-5 shadow-[0_20px_45px_-35px_rgba(15,23,42,0.45)]">
                  <div className="space-y-4">
                    <p
                      className={`inline-flex rounded-full bg-ink/[0.03] px-3 py-1 text-sm font-medium ${feedbackStatusClass}`}
                    >
                      {feedbackStatus}
                    </p>
                    <div className="space-y-1.5">
                      <p className="text-xs font-semibold uppercase tracking-[0.14em] text-ink/45">
                        {isShortAnswer ? "Model answer" : "Correct answer"}
                      </p>
                      <p className="text-base leading-7 text-ink">
                        {sanitizeFeedbackText(feedback.correctAnswer)}
                      </p>
                    </div>
                    <div className="space-y-1.5">
                      <p className="text-xs font-semibold uppercase tracking-[0.14em] text-ink/45">
                        Explanation
                      </p>
                      <p className="text-base leading-7 text-ink/80">
                        {sanitizeFeedbackText(feedback.rationale)}
                      </p>
                    </div>
                  </div>
                  {isShortAnswer ? (
                    <p className="mt-4 text-sm leading-6 text-ink/60">
                      This is a model-answer review rather than an objective score.
                    </p>
                  ) : null}
                  <div className="mt-5 space-y-2">
                    <p className="text-xs font-semibold uppercase text-ink/40">Citations</p>
                    {feedback.citations.length > 0 ? (
                      feedback.citations.map((citation, index) => (
                        <div key={`${citation.label}-${index}`} className="space-y-1 rounded-xl border border-ink/10 bg-ink/[0.02] p-3">
                          <p className="text-xs font-medium text-ink/50">{citation.label}</p>
                          <p className="text-xs text-ink/60">{sanitizeFeedbackText(citation.excerpt)}</p>
                        </div>
                      ))
                    ) : (
                      <p className="text-xs text-ink/50">No supporting citation available.</p>
                    )}
                  </div>
                  <div className="mt-5 space-y-3 rounded-xl border border-ink/10 bg-ink/[0.02] p-4">
                    <div className="space-y-1">
                      <p className="text-sm font-medium text-ink">How was this question?</p>
                      <p className="text-xs text-ink/60">
                        Help improve SULCAI. Was this question useful? Choose the closest
                        reason or add a comment. Hide is separate and removes it from your
                        future practice and mock exams.
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      {questionFeedbackOptions.map((option) => (
                        <Button
                          key={option.value}
                          type="button"
                          size="sm"
                          variant={questionFeedback?.label === option.value ? "default" : "outline"}
                          onClick={() => startQuestionFeedback(option.value)}
                          disabled={isSavingQuestionFeedback || isHidingQuestion}
                        >
                          {option.label}
                        </Button>
                      ))}
                      <Button
                        type="button"
                        size="sm"
                        variant={isQuestionHidden ? "default" : "outline"}
                        onClick={startHideQuestion}
                        disabled={isQuestionHidden || isHidingQuestion}
                      >
                        {isQuestionHidden ? "Question hidden" : "Hide this question"}
                      </Button>
                    </div>
                    {showHideQuestionWarning ? (
                      <div className="space-y-3 rounded-lg border border-ink/10 bg-white p-3">
                        <div className="space-y-1">
                          <p className="text-sm font-medium text-ink">Hide this question?</p>
                          <p className="text-xs text-ink/60">
                            This question will be hidden from your future practice and mock exams.
                          </p>
                        </div>
                        <label className="flex items-center gap-2 text-xs text-ink/65">
                          <input
                            type="checkbox"
                            checked={hideWarningChoice}
                            onChange={(event) => setHideWarningChoice(event.target.checked)}
                          />
                          Never show this warning again
                        </label>
                        <div className="flex flex-wrap gap-2">
                          <Button
                            type="button"
                            size="sm"
                            onClick={() => void applyHideQuestion()}
                            disabled={isHidingQuestion}
                          >
                            Confirm hide
                          </Button>
                          <Button
                            type="button"
                            size="sm"
                            variant="outline"
                            onClick={() => {
                              setShowHideQuestionWarning(false);
                              setHideWarningChoice(suppressHideWarning);
                            }}
                            disabled={isHidingQuestion}
                          >
                            Cancel
                          </Button>
                        </div>
                      </div>
                    ) : null}
                    {pendingFeedbackLabel ? (
                      <div className="space-y-3 rounded-lg border border-ink/10 bg-white p-3">
                        <div className="space-y-1">
                          <p className="text-sm font-medium text-ink">
                            {getQuestionFeedbackLabel(pendingFeedbackLabel)}
                          </p>
                          <p className="text-xs text-ink/60">
                            {getFeedbackCommentPrompt(pendingFeedbackLabel)}
                          </p>
                        </div>
                        <Textarea
                          value={questionFeedbackComment}
                          onChange={(event) => setQuestionFeedbackComment(event.target.value)}
                          placeholder={
                            requiresNonEmptyFeedbackComment(pendingFeedbackLabel)
                              ? "Required comment"
                              : "Optional comment"
                          }
                          disabled={isSavingQuestionFeedback}
                        />
                        <div className="flex flex-wrap gap-2">
                          <Button
                            type="button"
                            size="sm"
                            onClick={submitQuestionFeedbackWithComment}
                            disabled={isSavingQuestionFeedback}
                          >
                            Submit feedback
                          </Button>
                          <Button
                            type="button"
                            size="sm"
                            variant="outline"
                            onClick={() => {
                              setPendingFeedbackLabel(null);
                              setQuestionFeedbackComment("");
                              setQuestionFeedbackStatus(null);
                            }}
                            disabled={isSavingQuestionFeedback}
                          >
                            Cancel
                          </Button>
                        </div>
                      </div>
                    ) : null}
                    {questionFeedbackStatus ? (
                      <p className="text-xs text-ink/60">{questionFeedbackStatus}</p>
                    ) : hideQuestionStatus ? (
                      <p className="text-xs text-ink/60">{hideQuestionStatus}</p>
                    ) : questionFeedback ? (
                      <p className="text-xs text-ink/60">
                        Saved as {getQuestionFeedbackLabel(questionFeedback.label) ?? "feedback"}.
                      </p>
                    ) : null}
                    {showQuestionStylePrompt ? (
                      <div className="space-y-3 rounded-lg border border-ink/10 bg-white p-3">
                        <p className="text-sm text-ink/75">
                          Thanks — this feedback helps improve future question generation.
                        </p>
                      </div>
                    ) : null}
                  </div>
                  <div className="mt-4 flex flex-wrap gap-2">
                    <Button onClick={moveToNextQuestion}>
                      {results.length >= sessionConfig.sessionLength ? "View session summary" : "Next question"}
                    </Button>
                    <Button type="button" variant="outline" onClick={endSession}>
                      End session
                    </Button>
                  </div>
                </div>
              )}
            </div>
          ) : (
            <p className="text-sm text-ink/60">{status ?? "No questions available for this session."}</p>
          )}
        </div>
      ) : null}

      {view === "summary" ? (
        <div className="space-y-4 rounded-2xl border border-ink/10 bg-white p-5 shadow-[0_20px_45px_-35px_rgba(15,23,42,0.45)]">
          <div>
            <p className="text-lg font-medium text-ink">Practice session summary</p>
            <p className="text-sm text-ink/60">A quick view of how this session went.</p>
          </div>

          <div className="grid gap-2 text-sm text-ink/80">
            <p>Total answered: {totalAnswered}</p>
            <p>Objective questions: {objectiveCorrect}/{objectiveTotal} correct</p>
            <p>Objective incorrect: {objectiveIncorrect}</p>
            <p>Short-answer reviewed: {shortAnswerReviewed}</p>
            <p>Strong match: {shortAnswerStrongMatch}</p>
            <p>Partial match: {shortAnswerPartialMatch}</p>
            <p>Needs review: {shortAnswerNeedsReview}</p>
          </div>

          {topIncorrectTopic && topIncorrectTopic[1] >= 2 ? (
            <p className="text-sm text-ink/70">
              You missed several questions related to: <span className="font-medium text-ink">{topIncorrectTopic[0]}</span>
            </p>
          ) : null}

          {status ? <p className="text-sm text-ink/60">{status}</p> : null}

          <Button onClick={resetSession}>Start another session</Button>
        </div>
      ) : null}
    </div>
  );
}
